<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<AssemblyName>PayrollEngine.Client.Tutorial.PayrollTestRunner</AssemblyName>
		<RootNamespace>PayrollEngine.Client.Tutorial.PayrollTestRunner</RootNamespace>
		<Description>Payroll Engine Client Tutorial Payroll Test Runner</Description>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="PayrunTest.json" />
	  <None Remove="PayrunTestFailure.json" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="PayrunTest.json" />
	  <EmbeddedResource Include="PayrunTestFailure.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="PayrollEngine.Serilog" Version="0.9.0-beta.15" />
		<PackageReference Include="PayrollEngine.Client.Services" Version="0.9.0-beta.15" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="xunit.v3" Version="3.2.2" />
		<PackageReference Include="xunit.v3.runner.common" Version="3.2.2" />
	</ItemGroup>

</Project>
